#!/bin/bash

CMAKE_CURRENT_BINARY_DIR=out

cabal run exe:daedalus -v0 -- \
      --compile-c++ \
      --inline-this=StandardEncodings.glyph \
      --out-dir="$CMAKE_CURRENT_BINARY_DIR" \
      --entry=PdfXRef.PdfEnd \
      --entry=PdfXRef.CrossRef \
      --entry=PdfDecl.TopDecl \
      --entry=PdfDecl.ObjStream \
      --entry=PdfValue.Value \
      --entry=PdfCrypto.EncryptionDict \
      --entry=NewTextExtract.TextInCatalog \
      --entry=TE.PdfCatalog \
      --entry=TE.CheckRef \
      --entry=StandardEncodings.StdEncodings \
      "../spec/PdfCos.ddl"

