#!/bin/bash

VM="nessy.dev.galois.com"
VM_PATH="/media/data/raw"

if  [ $# == 0 ]; then
  echo "Need a corpus.  Some of these may work:"
  for i in $(ssh "$VM" "ls -d $VM_PATH/*/"); do basename $i; done
  exit 1
fi

for CORPUS in $*; do
  echo "Downloading $CORPUS"
  rsync -avz "$VM:$VM_PATH/$CORPUS" pdf_tests/
done

