#!/bin/bash
ACTUAL=pdf_tests_actual
EXPECTED=pdf_tests_expected

if [ $# -ne 1 ]; then
  echo "Usage $0 FILE"
  exit 1
fi

TEST=$1
echo "$TEST"

TEST_DIR=$(dirname "$TEST")
mkdir -p "$ACTUAL/$TEST_DIR"

ACTUAL_STDOUT="$ACTUAL/$TEST.stdout"
ACTUAL_STDERR="$ACTUAL/$TEST.stderr"
cabal exec pdf-hs-driver -- --faw $TEST > "$ACTUAL_STDOUT" 2> "$ACTUAL_STDERR"


EXPECTED_STDOUT="$EXPECTED/$TEST.stdout"
EXPECTED_STDERR="$EXPECTED/$TEST.stderr"
diff -q "$ACTUAL_STDOUT" "$EXPECTED_STDOUT"
diff -q "$ACTUAL_STDERR" "$EXPECTED_STDERR"
