#!/bin/bash
ACTUAL=pdf_tests_actual
EXPECTED=pdf_tests_expected

PDFHSDRIVER_DFLT="cabal exec pdf-hs-driver --"

diffonly=0
if [ "$1" = "--diffonly" ]; then
    shift
    diffonly=1
fi

if [ $# -ne 1 ]; then
  echo "Usage: $0 [ --diffonly ] FILE"
  exit 1
fi

TEST=$1
echo "$TEST"

TEST_DIR=$(dirname "$TEST")
mkdir -p "$ACTUAL/$TEST_DIR"

ACTUAL_STDOUT="$ACTUAL/$TEST.stdout"
ACTUAL_STDERR="$ACTUAL/$TEST.stderr"

EXPECTED_STDOUT="$EXPECTED/$TEST.stdout"
EXPECTED_STDERR="$EXPECTED/$TEST.stderr"

if [ $diffonly -eq 0 ]; then
  ${PDFHSDRIVER:-${PDFHSDRIVER_DFLT}} --faw $TEST > "$ACTUAL_STDOUT" 2> "$ACTUAL_STDERR"

  diff -q "$EXPECTED_STDOUT" "$ACTUAL_STDOUT" 
  diff -q "$EXPECTED_STDERR" "$ACTUAL_STDERR" 

else
    
  diff "$EXPECTED_STDOUT" "$ACTUAL_STDOUT" 
  diff "$EXPECTED_STDERR" "$ACTUAL_STDERR" 

fi  
    
  
