#!/bin/bash

set -e

DIR=test-bed
GEN_DIR=test-code
DDL=$1
ROOT=$(basename $DDL .ddl)

rm -rf $GEN_DIR
mkdir $GEN_DIR

cabal build daedalus
cabal exec daedalus -- \
  "$DDL"  \
  --out-dir="$GEN_DIR" \
  --compile-hs

CABAL="$DIR/test-bed.cabal"
cp "$DIR/test-bed.cabal.template" "$CABAL"
for i in $GEN_DIR/*.hs
do
  NAME=$(basename "$i" .hs)
  echo "  other-modules: $NAME" >> "$CABAL"
  cp "$i" "$DIR"
done

echo "import $ROOT" > "$DIR/Main.hs"
cat "$DIR/Main.hs.template" >> "$DIR/Main.hs"

pushd $DIR
cabal build exe:test-bed
popd
rm -rf test-code
