.PHONY: all

all: parser

CC=g++
CPPFLAGS=-I. $(shell pkg-config --cflags gmpxx) -DDDL_ENABLE_ERRORS
WARNS=-Wall -Wno-uninitialized
CXXFLAGS=--std=c++20 $(WARNS) -O1 -g -o parser -fsanitize=address
LIBS=$(shell pkg-config --libs gmpxx) -fsanitize=address

FILES=ddl/*.h main_parser.h main_parser.cpp main.cpp

parser: $(FILES)
	$(CC) $(CPPFLAGS) $(CXXFLAGS) main_parser.cpp main.cpp $(LIBS)

docs: $(FILES)
	doxygen Doxyfile

