#!/bin/bash

DIR=test-bed

set -e

if [ $# -gt 2 ] || [ $# -lt 1 ]; then
  echo "USAGE: $0 DDL_SPEC [FILE_TO_PARSE]"
  exit 1
fi

SPEC=$1
shift

cabal exec daedalus -- --out-dir="$DIR" --compile-c++ "$SPEC"
make -C "$DIR"
"$DIR/a.out" $*

