#!/bin/bash

echo "Regression Tests"
echo "================"
cd "$(dirname "$0")/../dex/tests"

pushd regression > /dev/null
./run-tests.sh "$@"
popd > /dev/null

echo ""
echo "Error Validation Tests"
echo "======================"
cd validation-errors
./run-tests.sh "$@"