.PHONY: all

all: parser docs

CC=g++
CPPFLAGS=-I.
WARNS=-Wall -Wno-uninitialized
CXXFLAGS=--std=c++17 $(WARNS) -O1 -g -o parser -fsanitize=address
LIBS=-lgmpxx -lgmp -fsanitize=address -static-libasan

FILES=ddl/*.h main_parser.h main_parser.cpp main.cpp

parser: $(FILES)
	$(CC) $(CPPFLAGS) $(CXXFLAGS) main_parser.cpp main.cpp $(LIBS)

docs: $(FILES)
	doxygen Doxyfile

