#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 DDL_FILE [INPUT]"
  exit
fi

source ./config

DDL=$1
shift

OUT_DIR=$(out_dir "$DDL")

if [ $# -eq 1 ]; then
  OUT_DIR="$OUT_DIR/$(basename $1)"
fi

./check.hs "$OUT_DIR"
