#!/bin/bash

source ./config

if [ $# -ne 1 ]; then
  echo "Usage: $0 DDL_FILE"
  exit
fi

DDL=$1

# --- Haskel -------------------------------------------------------------------

HS_DIR=$(hs_dir $DDL)

echo Compiling to Haskell
mkdir -p $HS_DIR
cp template_cabal_project "$HS_ROOT_DIR/cabal.project"
cabal exec daedalus -- --compile-hs --out-dir="$HS_DIR" "$DDL"

echo Building Haskell
pushd $HS_DIR
cabal build
ln -s $(cabal exec which $(name $DDL)) parser
popd


# --- C++ ----------------------------------------------------------------------
CPP_DIR=$(cpp_dir $DDL)

echo Compiling to C++
mkdir -p $CPP_DIR
cabal exec daedalus -- --compile-c++ --out-dir="$CPP_DIR" "$DDL"

echo Building C++
make -C "$CPP_DIR"


