#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 DDL_FILE INPUT"
  exit
fi

source ./config
DDL=$1
shift

OUT_DIR=$(out_dir "$DDL")

if [ $# -lt 1 ]; then
  RUN_OPTS="--run"
else
  RUN_OPTS="--interp=$1"
  OUT_DIR="$OUT_DIR/$(basename $1)"
fi

mkdir -p $OUT_DIR

echo "Running Daedalus"
cabal exec daedalus > "$OUT_DIR/daedalus" -- "$DDL" $RUN_OPTS

echo "Running Daedalus Core"
cabal exec daedalus > "$OUT_DIR/core" -- "$DDL" --core $RUN_OPTS

echo "Running Haskell"
$(hs_dir "$DDL")/parser $* > "$OUT_DIR/haskell"

echo "Running C++"
$(cpp_dir "$DDL")/parser $* > "$OUT_DIR/c++"


