#!/bin/bash

if [ $# -lt 3 ]; then
  echo "Usage: $0 BACKEND1 BACKEND2 DDL_FILE [INPUT]"
  exit
fi

source ./config

A=$1
shift
B=$1
shift
DDL=$1
shift

OUT_DIR=$(out_dir "$DDL")

if [ $# == 1 ]; then
  OUT_DIR="$OUT_DIR/$(basename $1)"
fi

F1=$(mktemp "${TMPDIR:-/tmp/}diffA.XXXXXXXX")
F2=$(mktemp "${TMPDIR:-/tmp/}diffB.XXXXXXXX")

jq . "$OUT_DIR/$A" > "$F1"
jq . "$OUT_DIR/$B" > "$F2"

diff "$F1" "$F2"

rm $F1
rm $F2




