name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Z3
      run: |
        wget --quiet https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3-4.8.10-x64-ubuntu-18.04.zip
        unzip z3-4.8.10-x64-ubuntu-18.04.zip
        cp z3-4.8.10-x64-ubuntu-18.04/bin/z3 .
        ./z3 --version


    -name: Test Z3
      run: |
        pwd
        ls
        ./z3 --version

    - uses: actions/setup-haskell@v1
      id: setup-haskell
      with:
        ghc-version: '8.8.3'
        cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-cabal
      with:
        path: |
          ${{ steps.setup-haskell.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests
    - name: Build Talos
      run: cabal build --enable-tests exe:talos
    - name: Run Talos tests
      run: cabal test talos-tests --test-options="--solver=./z3"

    - name: Build Daedalus
      run: cabal build --enable-tests exe:daedalus
    - name: Build ICC Parser
      run: cabal build exe:icc-parser
    - name: Build PDF driver
      run: cabal build exe:pdf-hs-driver
    - name: Build PDF dom
      run: cabal build exe:pdf-dom
    - name: Run Daedalus tests
      run: cabal test daedalus-tests
